//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMVCWithEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
        public int BillsID { get; set; }

        [Required]
        public int OrderID { get; set; }

        [Required]
        public int RestuarantID { get; set; }

        [Required]
        public double BillAmount { get; set; }

        [Required]
        public int CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderInfo OrderInfo { get; set; }
        public virtual RestaurantDetail RestaurantDetail { get; set; }
    }
}
