//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMVCWithEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DiningTableTrack
    {
        public int DiningTableTrackID { get; set; }

        [Required]
        public Nullable<int> DiningTableID { get; set; }

        [Required]
        public string TableStatus { get; set; }
    
        public virtual DiningTable DiningTable { get; set; }
    }
}
