//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMVCWithEF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Data.SqlClient;

    public partial class RestaurantEntities1 : DbContext
    {
        public RestaurantEntities1()
            : base("name=RestaurantEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Cuisine> Cuisines { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DiningTable> DiningTables { get; set; }
        public virtual DbSet<DiningTableTrack> DiningTableTracks { get; set; }
        public virtual DbSet<OrderInfo> OrderInfoes { get; set; }
        public virtual DbSet<RestaurantDetail> RestaurantDetails { get; set; }
        public virtual DbSet<RestaurantMenuItem> RestaurantMenuItems { get; set; }
        public virtual DbSet<Vw_CuisineDetails> Vw_CuisineDetails { get; set; }
    
        [DbFunction("RestaurantEntities1", "BillsTableFunction")]
        public virtual IQueryable<BillsTableFunction_Result> BillsTableFunction(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<BillsTableFunction_Result>("[RestaurantEntities1].[BillsTableFunction](@OrderID)", orderIDParameter);
        }
    
        public virtual int Bills_D(Nullable<int> billsID)
        {
            var billsIDParameter = billsID.HasValue ?
                new ObjectParameter("BillsID", billsID) :
                new ObjectParameter("BillsID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Bills_D", billsIDParameter);
        }
    
        public virtual int Bills_I(Nullable<int> orderID, Nullable<int> customerID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Bills_I", orderIDParameter, customerIDParameter);
        }
    
        public virtual int Cuisine_D(Nullable<int> cuisineID, Nullable<int> restuarantID, string cuisineName)
        {
            var cuisineIDParameter = cuisineID.HasValue ?
                new ObjectParameter("CuisineID", cuisineID) :
                new ObjectParameter("CuisineID", typeof(int));
    
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var cuisineNameParameter = cuisineName != null ?
                new ObjectParameter("CuisineName", cuisineName) :
                new ObjectParameter("CuisineName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cuisine_D", cuisineIDParameter, restuarantIDParameter, cuisineNameParameter);
        }
    
        public virtual int Cuisine_I(Nullable<int> restuarantID, string cuisineName)
        {
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var cuisineNameParameter = cuisineName != null ?
                new ObjectParameter("CuisineName", cuisineName) :
                new ObjectParameter("CuisineName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cuisine_I", restuarantIDParameter, cuisineNameParameter);
        }
    
        public virtual int Cuisine_IU(Nullable<int> cuisineID, Nullable<int> restuarantID, string cuisineName)
        {
            var cuisineIDParameter = cuisineID.HasValue ?
                new ObjectParameter("CuisineID", cuisineID) :
                new ObjectParameter("CuisineID", typeof(int));
    
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var cuisineNameParameter = cuisineName != null ?
                new ObjectParameter("CuisineName", cuisineName) :
                new ObjectParameter("CuisineName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cuisine_IU", cuisineIDParameter, restuarantIDParameter, cuisineNameParameter);
        }
    
        public virtual int Cuisine_U(Nullable<int> cuisineID, Nullable<int> restuarantID, string cuisineName)
        {
            var cuisineIDParameter = cuisineID.HasValue ?
                new ObjectParameter("CuisineID", cuisineID) :
                new ObjectParameter("CuisineID", typeof(int));
    
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var cuisineNameParameter = cuisineName != null ?
                new ObjectParameter("CuisineName", cuisineName) :
                new ObjectParameter("CuisineName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cuisine_U", cuisineIDParameter, restuarantIDParameter, cuisineNameParameter);
        }
    
        public virtual int Customer_D(Nullable<int> customerID, Nullable<int> restaurantID, string customerName, string mobileNo)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var restaurantIDParameter = restaurantID.HasValue ?
                new ObjectParameter("RestaurantID", restaurantID) :
                new ObjectParameter("RestaurantID", typeof(int));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Customer_D", customerIDParameter, restaurantIDParameter, customerNameParameter, mobileNoParameter);
        }
    
        public virtual int Customer_I(Nullable<int> restuarantID, string customerName, string mobileNo)
        {
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Customer_I", restuarantIDParameter, customerNameParameter, mobileNoParameter);
        }
    
        public virtual int Customer_U(Nullable<int> customerID, Nullable<int> restuarantID, string customerName, string mobileNo)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Customer_U", customerIDParameter, restuarantIDParameter, customerNameParameter, mobileNoParameter);
        }
    
        public virtual int DiningTable_D(Nullable<int> diningTableID)
        {
            var diningTableIDParameter = diningTableID.HasValue ?
                new ObjectParameter("DiningTableID", diningTableID) :
                new ObjectParameter("DiningTableID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DiningTable_D", diningTableIDParameter);
        }
    
        public virtual int DiningTable_I(Nullable<int> restuarantID, string diningLocation)
        {
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var diningLocationParameter = diningLocation != null ?
                new ObjectParameter("DiningLocation", diningLocation) :
                new ObjectParameter("DiningLocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DiningTable_I", restuarantIDParameter, diningLocationParameter);
        }
    
        public virtual int DiningTable_U(Nullable<int> diningTableID, Nullable<int> restuarantID, string diningLocation)
        {
            var diningTableIDParameter = diningTableID.HasValue ?
                new ObjectParameter("DiningTableID", diningTableID) :
                new ObjectParameter("DiningTableID", typeof(int));
    
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var diningLocationParameter = diningLocation != null ?
                new ObjectParameter("DiningLocation", diningLocation) :
                new ObjectParameter("DiningLocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DiningTable_U", diningTableIDParameter, restuarantIDParameter, diningLocationParameter);
        }
    
        public virtual int DiningTableTrack_I(Nullable<int> diningTableID, string tableStatus)
        {
            var diningTableIDParameter = diningTableID.HasValue ?
                new ObjectParameter("DiningTableID", diningTableID) :
                new ObjectParameter("DiningTableID", typeof(int));
    
            var tableStatusParameter = tableStatus != null ?
                new ObjectParameter("TableStatus", tableStatus) :
                new ObjectParameter("TableStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DiningTableTrack_I", diningTableIDParameter, tableStatusParameter);
        }
    
        public virtual int OrderInfo_D(Nullable<int> orderID, Nullable<System.DateTime> orderDate, Nullable<int> restuarantID, Nullable<int> menuItemID, Nullable<int> itemQuantity, Nullable<double> orderAmount, Nullable<int> diningTableID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(System.DateTime));
    
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var menuItemIDParameter = menuItemID.HasValue ?
                new ObjectParameter("MenuItemID", menuItemID) :
                new ObjectParameter("MenuItemID", typeof(int));
    
            var itemQuantityParameter = itemQuantity.HasValue ?
                new ObjectParameter("ItemQuantity", itemQuantity) :
                new ObjectParameter("ItemQuantity", typeof(int));
    
            var orderAmountParameter = orderAmount.HasValue ?
                new ObjectParameter("OrderAmount", orderAmount) :
                new ObjectParameter("OrderAmount", typeof(double));
    
            var diningTableIDParameter = diningTableID.HasValue ?
                new ObjectParameter("DiningTableID", diningTableID) :
                new ObjectParameter("DiningTableID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OrderInfo_D", orderIDParameter, orderDateParameter, restuarantIDParameter, menuItemIDParameter, itemQuantityParameter, orderAmountParameter, diningTableIDParameter);
        }
    
        public virtual int OrderInfo_I(Nullable<System.DateTime> orderDate, Nullable<int> restuarantID, Nullable<int> menuItemID, Nullable<int> itemQuantity, Nullable<double> orderAmount, Nullable<int> diningTableID)
        {
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(System.DateTime));
    
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var menuItemIDParameter = menuItemID.HasValue ?
                new ObjectParameter("MenuItemID", menuItemID) :
                new ObjectParameter("MenuItemID", typeof(int));
    
            var itemQuantityParameter = itemQuantity.HasValue ?
                new ObjectParameter("ItemQuantity", itemQuantity) :
                new ObjectParameter("ItemQuantity", typeof(int));
    
            var orderAmountParameter = orderAmount.HasValue ?
                new ObjectParameter("OrderAmount", orderAmount) :
                new ObjectParameter("OrderAmount", typeof(double));
    
            var diningTableIDParameter = diningTableID.HasValue ?
                new ObjectParameter("DiningTableID", diningTableID) :
                new ObjectParameter("DiningTableID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OrderInfo_I", orderDateParameter, restuarantIDParameter, menuItemIDParameter, itemQuantityParameter, orderAmountParameter, diningTableIDParameter);
        }
    
        public virtual int OrderInfo_U(Nullable<int> orderID, Nullable<System.DateTime> orderDate, Nullable<int> restuarantID, Nullable<int> menuItemID, Nullable<int> itemQuantity, Nullable<double> orderAmount, Nullable<int> diningTableID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(System.DateTime));
    
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var menuItemIDParameter = menuItemID.HasValue ?
                new ObjectParameter("MenuItemID", menuItemID) :
                new ObjectParameter("MenuItemID", typeof(int));
    
            var itemQuantityParameter = itemQuantity.HasValue ?
                new ObjectParameter("ItemQuantity", itemQuantity) :
                new ObjectParameter("ItemQuantity", typeof(int));
    
            var orderAmountParameter = orderAmount.HasValue ?
                new ObjectParameter("OrderAmount", orderAmount) :
                new ObjectParameter("OrderAmount", typeof(double));
    
            var diningTableIDParameter = diningTableID.HasValue ?
                new ObjectParameter("DiningTableID", diningTableID) :
                new ObjectParameter("DiningTableID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OrderInfo_U", orderIDParameter, orderDateParameter, restuarantIDParameter, menuItemIDParameter, itemQuantityParameter, orderAmountParameter, diningTableIDParameter);
        }
    
        public virtual int RestaurantDetails_D(Nullable<int> restuarantID, string restaurantName, string restaurantAddress, string mobileNo)
        {
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var restaurantNameParameter = restaurantName != null ?
                new ObjectParameter("RestaurantName", restaurantName) :
                new ObjectParameter("RestaurantName", typeof(string));
    
            var restaurantAddressParameter = restaurantAddress != null ?
                new ObjectParameter("RestaurantAddress", restaurantAddress) :
                new ObjectParameter("RestaurantAddress", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RestaurantDetails_D", restuarantIDParameter, restaurantNameParameter, restaurantAddressParameter, mobileNoParameter);
        }
    
        public virtual ObjectResult<string> RestaurantDetails_I(string restaurantName, string restaurantAddress, string mobileNo)
        {
            var restaurantNameParameter = restaurantName != null ?
                new ObjectParameter("RestaurantName", restaurantName) :
                new ObjectParameter("RestaurantName", typeof(string));
    
            var restaurantAddressParameter = restaurantAddress != null ?
                new ObjectParameter("RestaurantAddress", restaurantAddress) :
                new ObjectParameter("RestaurantAddress", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("RestaurantDetails_I", restaurantNameParameter, restaurantAddressParameter, mobileNoParameter);
        }
    
        public virtual int RestaurantDetails_U(Nullable<int> restuarantID, string restaurantName, string restaurantAddress, string mobileNo)
        {
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            var restaurantNameParameter = restaurantName != null ?
                new ObjectParameter("RestaurantName", restaurantName) :
                new ObjectParameter("RestaurantName", typeof(string));
    
            var restaurantAddressParameter = restaurantAddress != null ?
                new ObjectParameter("RestaurantAddress", restaurantAddress) :
                new ObjectParameter("RestaurantAddress", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RestaurantDetails_U", restuarantIDParameter, restaurantNameParameter, restaurantAddressParameter, mobileNoParameter);
        }
    
        public virtual int RestaurantMenuItem_D(Nullable<int> menuItemID, Nullable<int> cuisineID, string itemName, Nullable<double> itemPrice)
        {
            var menuItemIDParameter = menuItemID.HasValue ?
                new ObjectParameter("MenuItemID", menuItemID) :
                new ObjectParameter("MenuItemID", typeof(int));
    
            var cuisineIDParameter = cuisineID.HasValue ?
                new ObjectParameter("CuisineID", cuisineID) :
                new ObjectParameter("CuisineID", typeof(int));
    
            var itemNameParameter = itemName != null ?
                new ObjectParameter("ItemName", itemName) :
                new ObjectParameter("ItemName", typeof(string));
    
            var itemPriceParameter = itemPrice.HasValue ?
                new ObjectParameter("ItemPrice", itemPrice) :
                new ObjectParameter("ItemPrice", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RestaurantMenuItem_D", menuItemIDParameter, cuisineIDParameter, itemNameParameter, itemPriceParameter);
        }
    
        public virtual int RestaurantMenuItem_I(Nullable<int> cuisineID, string itemName, Nullable<double> itemPrice)
        {
            var cuisineIDParameter = cuisineID.HasValue ?
                new ObjectParameter("CuisineID", cuisineID) :
                new ObjectParameter("CuisineID", typeof(int));
    
            var itemNameParameter = itemName != null ?
                new ObjectParameter("ItemName", itemName) :
                new ObjectParameter("ItemName", typeof(string));
    
            var itemPriceParameter = itemPrice.HasValue ?
                new ObjectParameter("ItemPrice", itemPrice) :
                new ObjectParameter("ItemPrice", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RestaurantMenuItem_I", cuisineIDParameter, itemNameParameter, itemPriceParameter);
        }
    
        public virtual int RestaurantMenuItem_U(Nullable<int> menuItemID, Nullable<int> cuisineID, string itemName, Nullable<double> itemPrice)
        {
            var menuItemIDParameter = menuItemID.HasValue ?
                new ObjectParameter("MenuItemID", menuItemID) :
                new ObjectParameter("MenuItemID", typeof(int));
    
            var cuisineIDParameter = cuisineID.HasValue ?
                new ObjectParameter("CuisineID", cuisineID) :
                new ObjectParameter("CuisineID", typeof(int));
    
            var itemNameParameter = itemName != null ?
                new ObjectParameter("ItemName", itemName) :
                new ObjectParameter("ItemName", typeof(string));
    
            var itemPriceParameter = itemPrice.HasValue ?
                new ObjectParameter("ItemPrice", itemPrice) :
                new ObjectParameter("ItemPrice", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RestaurantMenuItem_U", menuItemIDParameter, cuisineIDParameter, itemNameParameter, itemPriceParameter);
        }
    
        public virtual ObjectResult<UFDTableStatus_Result> UFDTableStatus(Nullable<int> restuarantID)
        {
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UFDTableStatus_Result>("UFDTableStatus", restuarantIDParameter);
        }
    
        public virtual ObjectResult<USPDayWiseAmount_Result> USPDayWiseAmount(Nullable<int> restuarantID)
        {
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USPDayWiseAmount_Result>("USPDayWiseAmount", restuarantIDParameter);
        }
    
        public virtual int USPDisplayCustomerDetails(string filterBy, string orderBy)
        {
            var filterByParameter = filterBy != null ?
                new ObjectParameter("FilterBy", filterBy) :
                new ObjectParameter("FilterBy", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USPDisplayCustomerDetails", filterByParameter, orderByParameter);
        }
    
        public virtual ObjectResult<USPYearTotalAmount_Result> USPYearTotalAmount(Nullable<int> restuarantID)
        {
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USPYearTotalAmount_Result>("USPYearTotalAmount", restuarantIDParameter);
        }
    
        public virtual ObjectResult<USPYearTotalAmount1_Result> USPYearTotalAmount1(Nullable<int> restuarantID)
        {
            var restuarantIDParameter = restuarantID.HasValue ?
                new ObjectParameter("RestuarantID", restuarantID) :
                new ObjectParameter("RestuarantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USPYearTotalAmount1_Result>("USPYearTotalAmount1", restuarantIDParameter);
        }

        internal object SqlQuery(string v, SqlParameter sqlParameter)
        {
            throw new NotImplementedException();
        }
    }
}
