//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMVCWithEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderInfo()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int OrderID { get; set; }

        [Required(ErrorMessage ="Enter today's date")]
        //[RegularExpression(@"^(19|20)\d\d[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])$",ErrorMessage ="Please enter today's date with format as YYYY-MM-DD")]
        public System.DateTime OrderDate { get; set; }

        [Required]
        public int RestuarantID { get; set; }

        [Required]
        public int MenuItemID { get; set; }

        [Required]
        [RegularExpression(@"^[1-9][0-9]*$", ErrorMessage = "Item Price should be greater than 0")]
        public int ItemQuantity { get; set; }

        [Required]
        public double OrderAmount { get; set; }

        [Required]
        public int DiningTableID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual DiningTable DiningTable { get; set; }
        public virtual RestaurantMenuItem RestaurantMenuItem { get; set; }
        public virtual RestaurantDetail RestaurantDetail { get; set; }
    }
}
