//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantMVCWithEF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class RestaurantDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestaurantDetail()
        {
            this.Bills = new HashSet<Bill>();
            this.Cuisines = new HashSet<Cuisine>();
            this.Customers = new HashSet<Customer>();
            this.DiningTables = new HashSet<DiningTable>();
            this.OrderInfoes = new HashSet<OrderInfo>();
        }
    
        public int RestuarantID { get; set; }

        [Required]
        [Remote("ChkNameValidation", "RestaurantDetails", HttpMethod = "POST", ErrorMessage = "Restaurant Name already exists", AdditionalFields = "RestuarantID")]
        public string RestuarantName { get; set; }

        [Required]
        [RegularExpression(@"^[0-9].*", ErrorMessage = "1st letter should be numeric")]
        public string RestaurantAddress { get; set; }

        [Required]
        [Remote("ChkNoValidation", "RestaurantDetails", HttpMethod = "POST", ErrorMessage = "Mobile Number already exists", AdditionalFields = "RestuarantID")]
        [MinLength(10, ErrorMessage="Minimum 10 digits are required for Mobile Number")]
        public string MobileNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuisine> Cuisines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiningTable> DiningTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
    }
}
