//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillsID { get; set; }
        public int OrderID { get; set; }
        public int RestuarantID { get; set; }
        public double BillAmount { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderInfo OrderInfo { get; set; }
        public virtual RestaurantDetail RestaurantDetail { get; set; }
    }
}
